import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer/Footer";
import ThemeLoader from "../components/ThemeLoader"; // 👈 add this
import ThemeSwitcher from "../components/ThemeSwitcher"; // 👈 add this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/*  Load saved theme from localStorage */}
        <ThemeLoader />

        {/*  Optional: Add ThemeSwitcher button in header */}
        <header className="p-4 flex justify-end">
          <ThemeSwitcher />
        </header>

        <main className="flex-1">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
